services:
  postgres:
    image: postgres
    volumes:
      - ./mount-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgweb:
    image: sosedoff/pgweb
    command: pgweb --debug --url=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable --listen=9000 --open-retry=10
    ports:
      - "9000:9000"
    depends_on:
      - postgres
  web:
    build:
      context: .
      dockerfile: dockerfiles/gui.Dockerfile
    command: python3 -m paintdry serve
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  updater:
    build:
      context: .
      dockerfile: dockerfiles/updater.Dockerfile
    volumes:
      - ./mount-state:/paintdry/mount-state
    environment:
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - postgres
  downloader:
    build:
      context: .
      dockerfile: dockerfiles/downloader.Dockerfile
    volumes:
      - ./mount-state:/paintdry/mount-state
